### PR TITLE
Require iOS 13, more refactoring as a result

### PR DESCRIPTION
**Pull request by yeahphil**

### CODE REVIEW

**Comment by Gregliest** [comment]
What's up with the fantastically enormous diff? I'm not really sure how to review this, maybe we just merge and test.

**Comment by yeahphil** [comment]
I think the huge diff is all because I moved Apollo from a swiftpm dependency to cocoapods, Pods/ has a checked in copy of the pods, and Apollo is massive.

If you can filter Pods/** out of the diff it should be pretty manageable (can the GitHub web viewer do that?)

**Comment by yeahphil** [comment]
Stuff up to e9dd3b4 is whatever -- just does what it says and mostly config & env without much code change. 

But I'd love to have someone besides me aware of e9dd3b4 in particular, b/c I had to update the way it authenticates GraphQL requests to match the new Apollo way of doing things.

**Comment by Gregliest** [comment]
Ok I had a look. Not really sure that I'm the best person to check your work, as I haven't used Apollo or GraphQL, and I haven't authenticated anything on iOS in years. But, I'm aware it changed :).

**Comment by Gregliest** [comment]
@yeahphil My build is failing with this error:
```
Error: Cannot find module '/Users/gregorylee/dev/aw-ios/Pods/Apollo/script
    s/apollo/node_modules/boolean/build/lib/boolean.js'. Please verify that 
    the package.json has a valid "main" entry
```
Any ideas?

**Pull request merged**
