### PR TITLE
Add a Gemfile for cocoapods, update OneSignal and Firebase pods

### PR DESCRIPTION
**Pull request by yeahphil**
- Add a Gemfile
- SwiftPM keeps wanting to rename this package
- Update OneSignal, Firebase pods

### CODE REVIEW

**Comment by yeahphil** [comment]
Before merging, should check that this doesn't break push notifications via OneSignal.

**Comment by Gregliest** [comment]
Hmm, how do we check that?

**Comment by yeahphil** [comment]
Dunno :)

I have no idea when push notifications are supposed to be sent or how to receive one — but if they still arrive I think we’re good.

**Comment by Gregliest** [comment]
I'm going to merge this and we can test on testflight.

**Pull request merged**
